import Header from "@/components/layout/Header";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-center">
        <Header />
        <main className="flex flex-col justify-center items-center">
          {children}
        </main>
      </body>
    </html>
  );
}
